app_name = "awesome web"

# possible values: DEBUG, INFO, WARNING, ERROR, FATAL
log_level = "DEBUG"
[app]
# 本地监听的端口
port = 2047
# 平台名称，支持gitee/github
platform = "github"
# Gitee/Github 的用户授权码
token = "token"
# 仓库所属空间地址(企业、组织或个人的地址path)
owner = "hezhizheng"
# 仓库路径(path)
repo="static-image-hosting"
# 文件的路径
path = ""
# 分支
branch = "master"
[mysql]
ip = "127.0.0.1"
port = 3306
user = "dj"
password = 123456
database = "awesome"

[redis]
ip = "127.0.0.1"
port = 7381
